<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnablePackageValidation>true</EnablePackageValidation>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>PureQL.CSharp.Model.Samples</PackageId>
    <RootNamespace>PureQL.CSharp.Model.Samples</RootNamespace>
    <AssemblyName>PureQL.CSharp.Model.Samples</AssemblyName>
    <Authors>Dmitry Kurochkin</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/kudima03/PureQL.CSharp.Model.Samples</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Pure.Primitives" Version="3.6.5" />
    <PackageReference Include="Pure.Primitives.String.Operations" Version="1.5.1" />
    <PackageReference Include="Pure.RelationalSchema.Samples" Version="0.1.0-preview.1.0.0" />
    <PackageReference Include="PureQL.CSharp.Model" Version="0.1.0-preview.11.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
